default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff meiga tests --fix
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: isort
        name: isort
        entry: isort meiga tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: black
        name: black
        entry: black meiga tests
        language: system
        types: [ python ]
        require_serial: true
        fail_fast: true

      - id: pyupgrade
        name: Pyupgrade
        entry: pyupgrade --py37-plus
        types: [ python ]
        language: system
        exclude: ^docs/.*$
        fail_fast: true
