repos:

  - repo: local
    hooks:
      # Linter
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]

      - id: flake8
        name: flake8
        entry: flake8 meiga tests
        language: system
        types: [ python ]

      - id: isort
        name: isort
        entry: isort .
        language: system
        types: [ python ]
