name: ci

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'VERSION'
    branches: 
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: '**/*requirements.txt'
    - name: Install dependencies
      run: |
        pip install lume
        lume -install
    - name: Lint
      run: lume -lint
    - name: Static Analysis
      run: lume -static-analysis
    - name: Tests
      run: lume -test
    - name: Check Installation (--no-binary)
      run: lume -check-no-binary-installation
  test-imports:
    strategy:
      matrix:
        os: [ macOS-latest, ubuntu-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11-dev"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install latest version of meiga from code (without other dependencies as lume)
        run: pip install -e .
      - name: Check imports
        run: python -c "from meiga import Error, Success, Failure, Result; from meiga.decorators import meiga"