name: coverage

on:
  push:
    paths-ignore:
      - '*.md'
      - 'meiga/VERSION'
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: pip
        cache-dependency-path: pyproject.toml
    - uses: astral-sh/setup-uv@v2
    - name: Install dependencies
      run: |
        uv pip install lume
        lume -install
    - name: Coverage
      run: lume -coverage
    - uses: codecov/codecov-action@v2
      with:
        files: output/coverage/cobertura_coverage.xml
        name: meiga
        fail_ci_if_error: true
