name: pypi

on:
  release:
    types: [published]

jobs:
  get-version:
    uses: alice-biometrics/actions/.github/workflows/get-version.yml@main
    with:
      type: release
  publish:
    needs: get-version
    uses: alice-biometrics/actions/.github/workflows/publish-pypi.yml@feature/add-support-to-pyproject-toml-projects-to-publish-pypi
    with:
      package_name: meiga
      version: ${{ needs.get-version.outputs.version }}
    secrets:
      username: ${{ secrets.PYPI_TOKEN_USERNAME }}
      password: ${{ secrets.PYPI_TOKEN_PASSWORD_MEIGA }}
      github_access_token: ${{ secrets.PUBLIC_GITHUB_ACCESS_TOKEN }}
