name: pypi

on:
  release:
    types: [published]

env:
  TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
  TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  PACKAGE_NAME: meiga

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Set RELEASE_VERSION
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
    - name: Update VERSION file
      run: echo ${RELEASE_VERSION} > ${PACKAGE_NAME}/VERSION
    - name: Install dependencies
      run: pip install setuptools wheel twine
    - name: Build and publish
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
    - name: Git - Add VERSION File
      run: git add ${PACKAGE_NAME}/VERSION
    - name: Git - Commit VERSION File
      run: |
        git config --global user.email "dev@alicebiometrics.com"
        git config --global user.name "ALiCE Biometrics"
        git commit -m "Update version to ${RELEASE_VERSION}"
    - name: Push changes
      uses: alice-biometrics/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
